services:
  webserver:
    build:
      context: ..
      dockerfile: lab2_concurrent_http/Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      USE_LOCK: "1"
      RATE_LIMIT: "5"
      WINDOW_SEC: "1.0"
      PYTHONPATH: "/app"
    volumes:
      - ..:/app
    command: ["python", "lab2_concurrent_http/server_mt.py", "lab1_http/www"]